### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by dabanhfreak** [StaticMania/hugo-cohub#11]
Can't seem to install
I'm on Fedora using Hugo snap 0.115

```
$ git submodule add git@github.com:StaticMania/hugo-coHub.git themes/coHub
Cloning into '/home/user/cohub/themes/coHub'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:StaticMania/hugo-coHub.git' into submodule path '/home/user/cohub/themes/coHub' failed
```

**Comment by jandusek** [comment]
You'll need to either [add ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to your github account or use https:

`git submodule add https://github.com/StaticMania/hugo-cohub.git themes/coHub`
